#!/bin/busybox sh

rescue_shell() {
    echo "Something went wrong. Dropping to a shell."
    /bin/busybox --install -s
    exec sh
}

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys

echo "CRYPTSETUP"
 
/sbin/cryptsetup luksOpen /dev/sda3 gentoo-root || rescue_shell

echo "MOUNTING"
# Mount the root filesystem.
mount -o ro /dev/mapper/gentoo-root /mnt/root || rescue_shell
 
# Clean up.
#shouldn't this also be done by switch_root
umount /proc
umount /sys
 
# Boot the real root.
exec switch_root /mnt/root /sbin/init

